/*
 *  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 * 
 *  Copyright @2019 Jerome Lelasseux. All rights reserved.
 *
 *  This file is part of the JJazzLabX software.
 *   
 *  JJazzLabX is free software: you can redistribute it and/or modify
 *  it under the terms of the Lesser GNU General Public License (LGPLv3) 
 *  as published by the Free Software Foundation, either version 3 of the License, 
 *  or (at your option) any later version.
 *
 *  JJazzLabX is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 * 
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with JJazzLabX.  If not, see <https://www.gnu.org/licenses/>
 * 
 *  Contributor(s): 
 */
package org.jjazz.helpers;

import java.util.List;
import java.util.logging.Logger;
import org.jjazz.midimix.MidiMix;
import org.jjazz.rhythm.api.RhythmVoice;
import org.openide.windows.WindowManager;

/**
 * Helper dialog to propose Drums rerouting when it's relevant.
 */
public class DrumsReroutingDialog extends javax.swing.JDialog
{

    public enum ReroutingChoice
    {
        CANCEL, REROUTE, DONT_REROUTE
    };
    private ReroutingChoice choice;
    private static final Logger LOGGER = Logger.getLogger(DrumsReroutingDialog.class.getSimpleName());

    protected DrumsReroutingDialog()
    {
        super(WindowManager.getDefault().getMainWindow(), "Drums channels rerouting", true);
        choice = ReroutingChoice.CANCEL;
        initComponents();
        setLocationRelativeTo(WindowManager.getDefault().getMainWindow());
    }

    /**
     *
     * @return The user choice on this dialog.
     */
    public ReroutingChoice getUserChoice()
    {
        return choice;
    }

    /**
     * @return True if user checked "Remember my choice"
     */
    public boolean isRememberChoiceSelected()
    {
        return cb_rememberMyChoice.isSelected();
    }

    /**
     * Preset the dialog for the specified channels.
     * <p>
     * @param channels Channels which need rerouting
     * @param midiMix
     */
    public void preset(List<Integer> channels, MidiMix midiMix)
    {
        if (channels == null || channels.isEmpty() || midiMix == null)
        {
            throw new IllegalArgumentException("channels=" + channels + " midiMix=" + midiMix);
        }

        // Update dialog with channels info
        StringBuilder sb = new StringBuilder();
        sb.append("<HTML>");
        for (int ch : channels)
        {
            RhythmVoice rv = midiMix.getKey(ch);
            sb.append("- Midi channel ").append(ch + 1).append(" : ").append(rv.getContainer().getName())
                    .append(" - ").append(rv.getName());
            if (ch != channels.get(channels.size() - 1))
            {
                sb.append("<br/>");
            }
        }
        sb.append("</HTML>");
        lbl_reroutedChannels.setText(sb.toString());
        cb_rememberMyChoice.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * <p>
     * WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        cb_rememberMyChoice = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_help = new javax.swing.JTextArea();
        lbl_firstLine = new javax.swing.JLabel();
        lbl_reroutedChannels = new javax.swing.JLabel();
        pnl_buttons = new javax.swing.JPanel();
        btn_fix = new javax.swing.JButton();
        btn_skip = new javax.swing.JButton();
        btn_Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        org.openide.awt.Mnemonics.setLocalizedText(cb_rememberMyChoice, org.openide.util.NbBundle.getMessage(DrumsReroutingDialog.class, "DrumsReroutingDialog.cb_rememberMyChoice.text")); // NOI18N

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txt_help.setEditable(false);
        txt_help.setColumns(20);
        txt_help.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_help.setLineWrap(true);
        txt_help.setRows(5);
        txt_help.setText(org.openide.util.NbBundle.getMessage(DrumsReroutingDialog.class, "DrumsReroutingDialog.txt_help.text")); // NOI18N
        txt_help.setWrapStyleWord(true);
        txt_help.setOpaque(false);
        jScrollPane2.setViewportView(txt_help);

        lbl_firstLine.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(lbl_firstLine, org.openide.util.NbBundle.getMessage(DrumsReroutingDialog.class, "DrumsReroutingDialog.lbl_firstLine.text")); // NOI18N

        lbl_reroutedChannels.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(lbl_reroutedChannels, org.openide.util.NbBundle.getMessage(DrumsReroutingDialog.class, "DrumsReroutingDialog.lbl_reroutedChannels.text")); // NOI18N

        pnl_buttons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        org.openide.awt.Mnemonics.setLocalizedText(btn_fix, org.openide.util.NbBundle.getMessage(DrumsReroutingDialog.class, "DrumsReroutingDialog.btn_fix.text")); // NOI18N
        btn_fix.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_fixActionPerformed(evt);
            }
        });
        pnl_buttons.add(btn_fix);

        org.openide.awt.Mnemonics.setLocalizedText(btn_skip, org.openide.util.NbBundle.getMessage(DrumsReroutingDialog.class, "DrumsReroutingDialog.btn_skip.text")); // NOI18N
        btn_skip.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_skipActionPerformed(evt);
            }
        });
        pnl_buttons.add(btn_skip);

        org.openide.awt.Mnemonics.setLocalizedText(btn_Cancel, org.openide.util.NbBundle.getMessage(DrumsReroutingDialog.class, "DrumsReroutingDialog.btn_Cancel.text")); // NOI18N
        btn_Cancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_buttons, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_reroutedChannels)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_firstLine, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(cb_rememberMyChoice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Cancel)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_firstLine)
                .addGap(18, 18, 18)
                .addComponent(lbl_reroutedChannels)
                .addGap(27, 27, 27)
                .addComponent(pnl_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Cancel)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cb_rememberMyChoice)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void btn_skipActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_skipActionPerformed
   {//GEN-HEADEREND:event_btn_skipActionPerformed
       choice = ReroutingChoice.DONT_REROUTE;
       setVisible(false);
   }//GEN-LAST:event_btn_skipActionPerformed

   private void btn_fixActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_fixActionPerformed
   {//GEN-HEADEREND:event_btn_fixActionPerformed

       choice = ReroutingChoice.REROUTE;
       setVisible(false);
   }//GEN-LAST:event_btn_fixActionPerformed

    private void btn_CancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_CancelActionPerformed
    {//GEN-HEADEREND:event_btn_CancelActionPerformed
        choice = ReroutingChoice.CANCEL;
        setVisible(false);
    }//GEN-LAST:event_btn_CancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancel;
    private javax.swing.JButton btn_fix;
    private javax.swing.JButton btn_skip;
    private javax.swing.JCheckBox cb_rememberMyChoice;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_firstLine;
    private javax.swing.JLabel lbl_reroutedChannels;
    private javax.swing.JPanel pnl_buttons;
    private javax.swing.JTextArea txt_help;
    // End of variables declaration//GEN-END:variables

}
