/*
 *  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 * 
 *  Copyright @2019 Jerome Lelasseux. All rights reserved.
 *
 *  This file is part of the JJazzLab software.
 *   
 *  JJazzLab is free software: you can redistribute it and/or modify
 *  it under the terms of the Lesser GNU General Public License (LGPLv3) 
 *  as published by the Free Software Foundation, either version 3 of the License, 
 *  or (at your option) any later version.
 *
 *  JJazzLab is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 * 
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with JJazzLab.  If not, see <https://www.gnu.org/licenses/>
 * 
 *  Contributor(s): 
 */
package org.jjazz.ss_editorimpl.sptviewer;

import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.SwingUtilities;
import org.jjazz.rhythm.api.RhythmParameter;
import org.jjazz.ss_editor.sptviewer.spi.SptViewerSettings;
import org.jjazz.ss_editor.rpviewer.api.RpViewer;
import org.jjazz.songstructure.api.SongPart;
import org.jjazz.flatcomponents.api.FlatComponentsGlobalSettings;
import org.jjazz.ss_editor.api.SS_Editor;
import org.jjazz.ss_editor.rpviewer.api.RpViewerEditableRenderer;
import org.jjazz.ss_editor.rpviewer.api.RpViewerRenderer;
import org.jjazz.ss_editor.rpviewer.spi.RpViewerRendererFactory;
import org.jjazz.ss_editor.rpviewer.spi.DefaultRpViewerRendererFactory;
import org.jjazz.ss_editor.sptviewer.api.SptViewer;
import org.jjazz.ss_editor.sptviewer.api.SptViewerConfig;

/**
 * A SptViewer which just displays the RpViewers.
 */
public class SptViewerLow extends SptViewer
{

    private final DefaultRpViewerRendererFactory defaultRpRendererFactory;
    private static final Logger LOGGER = Logger.getLogger(SptViewerLow.class.getSimpleName());
    private SptViewerConfig uiConfig;


    public SptViewerLow(SS_Editor ssEditor, SongPart spt, SptViewerSettings settings, DefaultRpViewerRendererFactory factory)
    {
        Objects.requireNonNull(factory);
        super(ssEditor, spt, settings);

        defaultRpRendererFactory = factory;
        uiConfig = new SptViewerConfig();

        initComponents();


        // Create the RpViewers as required        
        setVisibleRps(getModel().getRhythm().getRhythmParameters());
    }


    @Override
    public void modelChanged()
    {
        // Nothing, RpViewer directly listen to their model
    }

    @Override
    public void settingsChanged()
    {
        // Nothing
    }

    @Override
    public SptViewerConfig getConfig()
    {
        return uiConfig;
    }

    @Override
    public void setConfig(SptViewerConfig newConfig)
    {
        Objects.requireNonNull(newConfig);
        if (!uiConfig.visibleRPs().equals(newConfig.visibleRPs()))
        {
            setVisibleRps(newConfig.visibleRPs());
        }

        uiConfig = newConfig;
    }

    @Override
    public List<RpViewer> getRpViewers()
    {
        ArrayList<RpViewer> rpvs = new ArrayList<>();
        for (Component c : pnl_RpEditors.getComponents())
        {
            if (c instanceof RpViewer rpViewer)
            {
                rpvs.add(rpViewer);
            }
        }
        return rpvs;
    }

    @Override
    public RpViewer getRpViewer(RhythmParameter<?> rp)
    {
        for (Component c : pnl_RpEditors.getComponents())
        {
            if (c instanceof RpViewer rpv)
            {
                if (rpv.getRpModel() == rp)
                {
                    return rpv;
                }
            }
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pnl_RpEditors = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBorder(settings.getDefaultBorder());
        setLayout(new java.awt.BorderLayout());

        pnl_RpEditors.setOpaque(false);
        pnl_RpEditors.setLayout(new javax.swing.BoxLayout(pnl_RpEditors, javax.swing.BoxLayout.Y_AXIS));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, "rpViewer1"); // NOI18N
        pnl_RpEditors.add(jLabel1);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, "rpViewer2"); // NOI18N
        pnl_RpEditors.add(jLabel2);

        add(pnl_RpEditors, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pnl_RpEditors;
    // End of variables declaration//GEN-END:variables


    // ---------------------------------------------------------------
    // Private methods
    // ---------------------------------------------------------------
    private void setVisibleRps(List<RhythmParameter<?>> rps)
    {
        var sptModel = getModel();
        var songModel = sptModel.getContainer().getSong();


        // Remove all RpViewers
        for (RpViewer rpv : getRpViewers())
        {
            unregisterRpViewer(rpv);
            rpv.cleanup();
        }
        pnl_RpEditors.removeAll();


        // Re-add RpViewers
        for (RhythmParameter<?> rp : rps)
        {
            if (sptModel.getRhythm().getRhythmParameters().contains(rp))
            {
                // Try to get first a specific factory for this rp
                RpViewerRendererFactory factory = RpViewerRendererFactory.findFactory(rp);
                if (factory == null)
                {
                    // Use default
                    factory = defaultRpRendererFactory;
                }
                assert factory != null;
                RpViewerRenderer renderer = factory.getRpViewerRenderer(songModel, sptModel, rp, settings.getRpViewerSettings());
                RpViewer rpv = new RpViewer(sptModel, rp, settings.getRpViewerSettings(), renderer);
                rpv.setController(controller);
                renderer.setRpViewer(rpv);


                registerRpViewer(rpv);
                rpv.setZoomVFactor(zoomVFactor);
                pnl_RpEditors.add((Component) rpv);
                pnl_RpEditors.add(Box.createRigidArea(new Dimension(0, 2)));
            } else
            {
                throw new IllegalArgumentException(
                        "rp=" + rp + " sptModel.getRhythm().getRhythmParameters()=" + sptModel.getRhythm().getRhythmParameters());
            }
        }
        pnl_RpEditors.revalidate();
        pnl_RpEditors.repaint();
    }

    private void registerRpViewer(RpViewer rpv)
    {
        rpv.addMouseListener(this);
        if (rpv.getRenderer() instanceof RpViewerEditableRenderer)
        {
            // Nothing: drag and mousewheel events should be ignored if RpViewer is directly editable
        } else
        {
            rpv.addMouseMotionListener(this);
            FlatComponentsGlobalSettings.getInstance().installChangeValueWithMouseWheelSupport(rpv, this);
        }
    }

    private void unregisterRpViewer(RpViewer rpv)
    {
        rpv.removeMouseListener(this);
        rpv.removeMouseMotionListener(this);
        rpv.removeMouseWheelListener(this);         // Sometimes useless but it's ok
    }


    private void redispatchEvent(java.awt.event.MouseEvent evt)
    {
        Container source = (Container) evt.getSource();
        MouseEvent parentEvent = SwingUtilities.convertMouseEvent(source, evt, this);
        this.dispatchEvent(parentEvent);
    }


}
