package org.jjazz.test.rhythm;

import org.jjazz.rpcustomeditor.spi.RpCustomEditor;
import org.jjazz.songstructure.api.SongPart;

/**
 *
 * @author Administrateur
 */
public class PanelEditor extends RpCustomEditor<RP_TestValue>
{

    public PanelEditor(RP_Test rp)
    {
        super(rp);
        initComponents();
    }

    @Override
    public void preset(RP_TestValue rpValue, SongPart spt)
    {
        setEditedRpValue(rpValue);
    }

    @Override
    public void setEditedRpValue(RP_TestValue rpValue)
    {
        knb_bassDrum.setValue(rpValue.getBassDrumOffset());
        knb_snare.setValue(rpValue.getSnareOffset());
        knb_hihat.setValue(rpValue.getHiHatOffset());
    }

    @Override
    public RP_TestValue getEditedRpValue()
    {
        RP_TestValue res = new RP_TestValue(knb_bassDrum.getValue(), knb_snare.getValue(), knb_hihat.getValue());
        return res;
    }

    @Override
    public void cleanup()
    {

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
     * this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        knb_bassDrum = new org.jjazz.ui.flatcomponents.FlatIntegerKnob();
        knb_snare = new org.jjazz.ui.flatcomponents.FlatIntegerKnob();
        knb_hihat = new org.jjazz.ui.flatcomponents.FlatIntegerKnob();

        javax.swing.GroupLayout knb_bassDrumLayout = new javax.swing.GroupLayout(knb_bassDrum);
        knb_bassDrum.setLayout(knb_bassDrumLayout);
        knb_bassDrumLayout.setHorizontalGroup(
            knb_bassDrumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        knb_bassDrumLayout.setVerticalGroup(
            knb_bassDrumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout knb_snareLayout = new javax.swing.GroupLayout(knb_snare);
        knb_snare.setLayout(knb_snareLayout);
        knb_snareLayout.setHorizontalGroup(
            knb_snareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        knb_snareLayout.setVerticalGroup(
            knb_snareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout knb_hihatLayout = new javax.swing.GroupLayout(knb_hihat);
        knb_hihat.setLayout(knb_hihatLayout);
        knb_hihatLayout.setHorizontalGroup(
            knb_hihatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        knb_hihatLayout.setVerticalGroup(
            knb_hihatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(knb_bassDrum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(knb_snare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(knb_hihat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(knb_hihat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(knb_snare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(knb_bassDrum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jjazz.ui.flatcomponents.FlatIntegerKnob knb_bassDrum;
    private org.jjazz.ui.flatcomponents.FlatIntegerKnob knb_hihat;
    private org.jjazz.ui.flatcomponents.FlatIntegerKnob knb_snare;
    // End of variables declaration//GEN-END:variables
}
