package org.jjazz.test.rhythm;

import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
import org.openide.windows.WindowManager;

/**
 *
 * @author Administrateur
 */
public class RP_TestEditorDialog extends javax.swing.JDialog
{

    private static RP_TestEditorDialog INSTANCE;

    private RP_TestValue resultValue;

    private static final Logger LOGGER = Logger.getLogger(RP_TestEditorDialog.class.getSimpleName());

    public static RP_TestEditorDialog getInstance()
    {
        synchronized (RP_TestEditorDialog.class)
        {
            if (INSTANCE == null)
            {
                INSTANCE = new RP_TestEditorDialog(WindowManager.getDefault().getMainWindow(), true);
            }
        }
        return INSTANCE;
    }

    /**
     * Creates new form RP_TestEditorDialog
     */
    public RP_TestEditorDialog(Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    public void preset(RP_TestValue value)
    {
        knb_bassDrum.setValue(value.getBassDrumOffset());
        knb_snare.setValue(value.getSnareOffset());
        knb_hihat.setValue(value.getHiHatOffset());
    }

    /**
     * The resulting value.
     *
     * @return Null if user cancelled the dialog.
     */
    public RP_TestValue getValue()
    {
        return resultValue;
    }

    // ======================================================================================
    // Private methods
    // ======================================================================================    
    /**
     * Overridden to add global key bindings
     *
     * @return
     */
    @Override
    protected JRootPane createRootPane()
    {
        JRootPane contentPane = new JRootPane();
        contentPane.getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT).put(KeyStroke.getKeyStroke("ENTER"), "actionOk");   //NOI18N
        contentPane.getActionMap().put("actionOk", new AbstractAction("OK")
        {

            @Override
            public void actionPerformed(ActionEvent e)
            {
                btn_OkActionPerformed(null);
            }
        });

        contentPane.getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT).put(KeyStroke.getKeyStroke("ESCAPE"), "actionCancel");   //NOI18N
        contentPane.getActionMap().put("actionCancel", new AbstractAction("Cancel")
        {

            @Override
            public void actionPerformed(ActionEvent e)
            {
                btn_CancelActionPerformed(null);
            }
        });
        return contentPane;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
     * this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        knb_bassDrum = new org.jjazz.ui.flatcomponents.FlatIntegerKnob();
        knb_snare = new org.jjazz.ui.flatcomponents.FlatIntegerKnob();
        knb_hihat = new org.jjazz.ui.flatcomponents.FlatIntegerKnob();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_Cancel = new javax.swing.JButton();
        btn_Ok = new javax.swing.JButton();

        knb_bassDrum.setLabel(org.openide.util.NbBundle.getBundle(RP_TestEditorDialog.class).getString("RP_TestEditorDialog.knb_bassDrum.label")); // NOI18N
        knb_bassDrum.setMaxValue(64);
        knb_bassDrum.setMinValue(-64);
        knb_bassDrum.setTooltipLabel(org.openide.util.NbBundle.getBundle(RP_TestEditorDialog.class).getString("RP_TestEditorDialog.knb_bassDrum.tooltipLabel")); // NOI18N
        knb_bassDrum.setValue(0);

        knb_snare.setLabel(org.openide.util.NbBundle.getBundle(RP_TestEditorDialog.class).getString("RP_TestEditorDialog.knb_snare.label")); // NOI18N
        knb_snare.setMaxValue(64);
        knb_snare.setMinValue(-64);
        knb_snare.setTooltipLabel(org.openide.util.NbBundle.getBundle(RP_TestEditorDialog.class).getString("RP_TestEditorDialog.knb_snare.tooltipLabel")); // NOI18N
        knb_snare.setValue(0);

        knb_hihat.setLabel(org.openide.util.NbBundle.getBundle(RP_TestEditorDialog.class).getString("RP_TestEditorDialog.knb_hihat.label")); // NOI18N
        knb_hihat.setMaxValue(64);
        knb_hihat.setMinValue(-64);
        knb_hihat.setTooltipLabel(org.openide.util.NbBundle.getBundle(RP_TestEditorDialog.class).getString("RP_TestEditorDialog.knb_hihat.tooltipLabel")); // NOI18N
        knb_hihat.setValue(0);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getBundle(RP_TestEditorDialog.class).getString("RP_TestEditorDialog.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getBundle(RP_TestEditorDialog.class).getString("RP_TestEditorDialog.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getBundle(RP_TestEditorDialog.class).getString("RP_TestEditorDialog.jLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btn_Cancel, org.openide.util.NbBundle.getBundle(RP_TestEditorDialog.class).getString("RP_TestEditorDialog.btn_Cancel.text")); // NOI18N
        btn_Cancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_CancelActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btn_Ok, org.openide.util.NbBundle.getBundle(RP_TestEditorDialog.class).getString("RP_TestEditorDialog.btn_Ok.text")); // NOI18N
        btn_Ok.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_OkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(knb_bassDrum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(knb_snare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addComponent(knb_hihat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Ok)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Cancel)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_Cancel, btn_Ok});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(knb_hihat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Cancel)
                    .addComponent(btn_Ok))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(knb_bassDrum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(knb_snare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_OkActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_OkActionPerformed
    {//GEN-HEADEREND:event_btn_OkActionPerformed
        resultValue = new RP_TestValue(knb_bassDrum.getValue(), knb_snare.getValue(), knb_hihat.getValue());
        setVisible(false);
    }//GEN-LAST:event_btn_OkActionPerformed

    private void btn_CancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_CancelActionPerformed
    {//GEN-HEADEREND:event_btn_CancelActionPerformed
        resultValue = null;
        setVisible(false);
    }//GEN-LAST:event_btn_CancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancel;
    private javax.swing.JButton btn_Ok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private org.jjazz.ui.flatcomponents.FlatIntegerKnob knb_bassDrum;
    private org.jjazz.ui.flatcomponents.FlatIntegerKnob knb_hihat;
    private org.jjazz.ui.flatcomponents.FlatIntegerKnob knb_snare;
    // End of variables declaration//GEN-END:variables
}
