/*
 *  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 * 
 *  Copyright @2019 Jerome Lelasseux. All rights reserved.
 *
 *  This file is part of the JJazzLabX software.
 *   
 *  JJazzLabX is free software: you can redistribute it and/or modify
 *  it under the terms of the Lesser GNU General Public License (LGPLv3) 
 *  as published by the Free Software Foundation, either version 3 of the License, 
 *  or (at your option) any later version.
 *
 *  JJazzLabX is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 * 
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with JJazzLabX.  If not, see <https://www.gnu.org/licenses/>
 * 
 *  Contributor(s): 
 */
package org.jjazz.helpers.midiwizard;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import javax.sound.midi.MidiDevice;
import javax.swing.JEditorPane;
import javax.swing.JPanel;
import javax.swing.event.HyperlinkEvent;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;

public final class MidiWizardVisualPanel_SfWin_1 extends JPanel
{

    private MidiDevice vmsDevice = null;

    /**
     * Creates new form StartupWizardVisualPanel1
     */
    public MidiWizardVisualPanel_SfWin_1()
    {
        initComponents();
    }

    @Override
    public String getName()
    {
        return "VirtualMidiSynth";
    }

    /**
     * @param md Can be null if not detected.
     */
    public void setVmsDevice(MidiDevice md)
    {
        vmsDevice = md;
        String msg1 = "JJazzLab must be connected to the VirtualMIDISynth Midi out device.<br/><br/>";
        String msg2 = "VirtualMIDISynth : " + ((vmsDevice == null) ? "<b>NOT DETECTED</b>" : md.getDeviceInfo().getName() + " > OK") + " <br/><br/>";
        String msg3 = "";
        if (vmsDevice == null)
        {
            msg3 = "You must download and install VirtualMIDISynth from <a href=\"https://coolsoft.altervista.org/virtualmidisynth\">www.coolsoft.altervista.org/virtualmidisynth</a>.<br/><br/>";
        }
        String msg4 = "For more information about using the JJazzLab-SoundFont consult the <a href=\"https://www.jjazzlab.com/en/doc\">online doc</a>";
        editorPane.setText(msg1 + msg2 + msg3 + msg4);
    }

    private void openInBrowser(URL url)
    {
        String errMsg = null;
        if (Desktop.isDesktopSupported())
        {
            try
            {
                Desktop.getDesktop().browse(url.toURI());
            } catch (URISyntaxException | IOException ex)
            {
                errMsg = ex.getLocalizedMessage();
            }
        } else
        {
            errMsg = "Open hyperlink in browser not supported";
        }
        if (errMsg != null)
        {
            NotifyDescriptor d = new NotifyDescriptor.Message(errMsg, NotifyDescriptor.ERROR_MESSAGE);
            DialogDisplayer.getDefault().notify(d);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
     * this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        ta_notUserOnlyToGetFont = new org.jjazz.helpers.midiwizard.WizardTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        editorPane = new javax.swing.JEditorPane();
        editorPane.putClientProperty(JEditorPane.HONOR_DISPLAY_PROPERTIES, Boolean.TRUE); // To make setFont work

        ta_notUserOnlyToGetFont.setEditable(false);
        ta_notUserOnlyToGetFont.setBackground(null);
        ta_notUserOnlyToGetFont.setColumns(20);
        ta_notUserOnlyToGetFont.setTabSize(2);

        jScrollPane2.setBackground(null);
        jScrollPane2.setBorder(null);

        editorPane.setEditable(false);
        editorPane.setBackground(null);
        editorPane.setBorder(null);
        editorPane.setEditorKit(JEditorPane.createEditorKitForContentType("text/html"));
        editorPane.setFont(ta_notUserOnlyToGetFont.getFont());
        editorPane.setText(org.openide.util.NbBundle.getMessage(MidiWizardVisualPanel_SfWin_1.class, "MidiWizardVisualPanel_SfWin_1.editorPane.text")); // NOI18N
        editorPane.addHyperlinkListener(new javax.swing.event.HyperlinkListener()
        {
            public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt)
            {
                editorPaneHyperlinkUpdate(evt);
            }
        });
        jScrollPane2.setViewportView(editorPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ta_notUserOnlyToGetFont, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 305, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ta_notUserOnlyToGetFont, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editorPaneHyperlinkUpdate(javax.swing.event.HyperlinkEvent evt)//GEN-FIRST:event_editorPaneHyperlinkUpdate
    {//GEN-HEADEREND:event_editorPaneHyperlinkUpdate
        if (evt.getEventType() == HyperlinkEvent.EventType.ACTIVATED)
        {
            openInBrowser(evt.getURL());
        }
    }//GEN-LAST:event_editorPaneHyperlinkUpdate

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JEditorPane editorPane;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jjazz.helpers.midiwizard.WizardTextArea ta_notUserOnlyToGetFont;
    // End of variables declaration//GEN-END:variables
}
