/*
 *  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 * 
 *  Copyright @2025 Jerome Lelasseux. All rights reserved.
 *
 *  This file is part of the JJazzLab software.
 *   
 *  JJazzLab is free software: you can redistribute it and/or modify
 *  it under the terms of the Lesser GNU General Public License (LGPLv3) 
 *  as published by the Free Software Foundation, either version 3 of the License, 
 *  or (at your option) any later version.
 *
 *  JJazzLab is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 * 
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with JJazzLab.  If not, see <https://www.gnu.org/licenses/>
 * 
 *  Contributor(s): 
 */
package org.jjazz.musiccontrolactions;

import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.KeyEvent;
import org.jjazz.musiccontrol.api.PlaybackSettings;
import org.jjazz.uiutilities.api.UIUtilities;
import org.openide.windows.WindowManager;

/**
 * Dialog to select transposition.
 * <p>
 * PlaybackSettings is directly updated when user interacts with UI -so he can immediatly understand the changes.
 */
public class TransposeDisplayedChordSymbolsDialog extends javax.swing.JDialog
{

    static private TransposeDisplayedChordSymbolsDialog INSTANCE;
    private int lastNonZeroTransposition = 2;
    private int cancelTransposition;

    public static TransposeDisplayedChordSymbolsDialog getInstance()
    {
        synchronized (TransposeDisplayedChordSymbolsDialog.class)
        {
            if (INSTANCE == null)
            {
                INSTANCE = new TransposeDisplayedChordSymbolsDialog(WindowManager.getDefault().getMainWindow(), true);
            }
        }
        return INSTANCE;
    }

    private TransposeDisplayedChordSymbolsDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();

        UIUtilities.installEnterKeyAction(this, () -> actionOK());
        UIUtilities.installEscapeKeyAction(this, () -> actionCancel());

        PlaybackSettings.getInstance().addPropertyChangeListener(PlaybackSettings.PROP_CHORD_SYMBOLS_DISPLAY_TRANSPOSITION, e -> transpositionChanged());
        transpositionChanged();

        pack();

        addComponentListener(new ComponentAdapter()
        {
            @Override
            public void componentShown(ComponentEvent e)
            {
                cb_enableTransposition.requestFocusInWindow();
                cancelTransposition = PlaybackSettings.getInstance().getChordSymbolsDisplayTransposition();
            }
        });

    }

    // ====================================================================================================
    // Private methods
    // ====================================================================================================
    /**
     * Get the key transposition value.
     * <p>
     *
     * @return
     */
    private int getDisplayTransposition()
    {
        return !cb_enableTransposition.isSelected() ? 0 : cmb_transposition.getSelectedIndex() + 1;
    }

    private void transpositionChanged()
    {
        int t = PlaybackSettings.getInstance().getChordSymbolsDisplayTransposition();
        cb_enableTransposition.setSelected(t != 0);
        cmb_transposition.setEnabled(t != 0);
        if (t != 0)
        {
            lastNonZeroTransposition = t;
            cmb_transposition.setSelectedIndex(t - 1);
        }
    }

    private void actionOK()
    {
        setVisible(false);
    }

    private void actionCancel()
    {
        PlaybackSettings.getInstance().setChordSymbolsDisplayTransposition(cancelTransposition);
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btn_Ok = new javax.swing.JButton();
        btn_Cancel = new javax.swing.JButton();
        cmb_transposition = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        helpTextArea1 = new org.jjazz.flatcomponents.api.HelpTextArea();
        cb_enableTransposition = new javax.swing.JCheckBox();

        setTitle(org.openide.util.NbBundle.getMessage(TransposeDisplayedChordSymbolsDialog.class, "TransposeDisplayedChordSymbolsDialog.title")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btn_Ok, org.openide.util.NbBundle.getMessage(TransposeDisplayedChordSymbolsDialog.class, "TransposeDisplayedChordSymbolsDialog.btn_Ok.text")); // NOI18N
        btn_Ok.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_OkActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btn_Cancel, org.openide.util.NbBundle.getMessage(TransposeDisplayedChordSymbolsDialog.class, "TransposeDisplayedChordSymbolsDialog.btn_Cancel.text")); // NOI18N
        btn_Cancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_CancelActionPerformed(evt);
            }
        });

        cmb_transposition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-1", "-2   (sax tenor Bb, trumpet Bb, ...)", "-3 ", "-4 ", "-5  (flute alto G, ...)", "-6 ", "-7", "-8", "-9   (sax alto Eb, ...)", "-10", "-11  (piccolo Db, ...)" }));
        cmb_transposition.setSelectedIndex(1);
        cmb_transposition.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmb_transpositionActionPerformed(evt);
            }
        });
        cmb_transposition.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                cmb_transpositionKeyPressed(evt);
            }
        });

        jScrollPane1.setBorder(null);

        helpTextArea1.setColumns(20);
        helpTextArea1.setRows(2);
        helpTextArea1.setText(org.openide.util.NbBundle.getMessage(TransposeDisplayedChordSymbolsDialog.class, "TransposeDisplayedChordSymbolsDialog.helpTextArea1.text")); // NOI18N
        jScrollPane1.setViewportView(helpTextArea1);

        org.openide.awt.Mnemonics.setLocalizedText(cb_enableTransposition, org.openide.util.NbBundle.getMessage(TransposeDisplayedChordSymbolsDialog.class, "TransposeDisplayedChordSymbolsDialog.cb_enableTransposition.text")); // NOI18N
        cb_enableTransposition.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cb_enableTranspositionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cb_enableTransposition)
                                .addGap(0, 124, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_Ok)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Cancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1))
                    .addComponent(cmb_transposition, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_Cancel, btn_Ok});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(cb_enableTransposition)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(cmb_transposition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Cancel)
                    .addComponent(btn_Ok))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_transpositionKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cmb_transpositionKeyPressed
    {//GEN-HEADEREND:event_cmb_transpositionKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER)
        {
            actionOK();
        }
    }//GEN-LAST:event_cmb_transpositionKeyPressed

    private void btn_OkActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_OkActionPerformed
    {//GEN-HEADEREND:event_btn_OkActionPerformed
        actionOK();
    }//GEN-LAST:event_btn_OkActionPerformed

    private void btn_CancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_CancelActionPerformed
    {//GEN-HEADEREND:event_btn_CancelActionPerformed
        actionCancel();
    }//GEN-LAST:event_btn_CancelActionPerformed

    private void cb_enableTranspositionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cb_enableTranspositionActionPerformed
    {//GEN-HEADEREND:event_cb_enableTranspositionActionPerformed
        PlaybackSettings.getInstance().setChordSymbolsDisplayTransposition(getDisplayTransposition());
    }//GEN-LAST:event_cb_enableTranspositionActionPerformed

    private void cmb_transpositionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmb_transpositionActionPerformed
    {//GEN-HEADEREND:event_cmb_transpositionActionPerformed
        PlaybackSettings.getInstance().setChordSymbolsDisplayTransposition(getDisplayTransposition());
    }//GEN-LAST:event_cmb_transpositionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancel;
    private javax.swing.JButton btn_Ok;
    private javax.swing.JCheckBox cb_enableTransposition;
    private javax.swing.JComboBox<String> cmb_transposition;
    private org.jjazz.flatcomponents.api.HelpTextArea helpTextArea1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
