/*
 *  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 *  Copyright @2019 Jerome Lelasseux. All rights reserved.
 *
 *  This file is part of the JJazzLab software.
 *
 *  JJazzLab is free software: you can redistribute it and/or modify
 *  it under the terms of the Lesser GNU General Public License (LGPLv3)
 *  as published by the Free Software Foundation, either version 3 of the License,
 *  or (at your option) any later version.
 *
 *  JJazzLab is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with JJazzLab.  If not, see <https://www.gnu.org/licenses/>
 *
 *  Contributor(s):
 */
package org.jjazz.uiutilities.api;

import java.util.Objects;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import org.jjazz.utilities.api.CheckedRunnable;
import org.openide.util.Exceptions;
import org.openide.windows.WindowManager;

/**
 * A simple "Please wait..." (or any other text) modal dialog.
 */
public class PleaseWaitDialog extends javax.swing.JDialog
{

    private final String text;
    private static final Logger LOGGER = Logger.getLogger(PleaseWaitDialog.class.getSimpleName());

    /**
     * Create and show a dialog.
     * <p>
     * Caller must hide and dispose the dialog when needed.
     *
     * @param text The text to be shown.
     * @return The created dialog.
     */
    public static PleaseWaitDialog show(String text)
    {
        Objects.requireNonNull(text);
        var dlg = new PleaseWaitDialog(text, null);
        dlg.setVisible(true);
        return dlg;
    }

    /**
     * Create and show a dialog, start the specified task and close the dialog when task is complete.
     *
     * @param text
     * @param task
     */
    public static void show(String text, Runnable task)
    {
        Objects.requireNonNull(task);
        ExecutorService executor = Executors.newSingleThreadExecutor();
        Future<?> future = executor.submit(new CheckedRunnable(task));
        show(text, future);
    }

    /**
     * Create and show a dialog which closes itself when the future is done.
     *
     * @param text
     * @param future
     */
    public static void show(String text, Future future)
    {
        Objects.requireNonNull(text);
        Objects.requireNonNull(future);
        var dlg = new PleaseWaitDialog(text, future);
        dlg.setVisible(true);
    }


    /**
     * Create and show a dialog which shows the specified text.
     *
     * @param text
     * @param future Can be null
     */
    private PleaseWaitDialog(String text, Future future)
    {
        super(WindowManager.getDefault().getMainWindow(), true);
        this.text = text;
        initComponents();
        setLocationRelativeTo(WindowManager.getDefault().getMainWindow());

        if (future != null)
        {
            SwingUtilities.invokeLater(() -> 
            {
                try
                {
                    future.get();
                } catch (InterruptedException ex)
                {
                    LOGGER.log(Level.WARNING, "PleaseWaitDialog() future task was interrupted ex={0}", ex.getMessage());
                } catch (ExecutionException ex)
                {
                    LOGGER.log(Level.WARNING, "PleaseWaitDialog() an unexpected error occured in future task ex={0}", ex.getMessage());
                    Exceptions.printStackTrace(ex);
                }
                setVisible(false);
                dispose();
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(114, 148, 163));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()+1f));
        jLabel1.setForeground(new java.awt.Color(246, 241, 241));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, text);
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
