/*
 * 
 *   DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *  
 *   Copyright @2019 Jerome Lelasseux. All rights reserved.
 * 
 *   This file is part of the JJazzLab software.
 *    
 *   JJazzLab is free software: you can redistribute it and/or modify
 *   it under the terms of the Lesser GNU General Public License (LGPLv3) 
 *   as published by the Free Software Foundation, either version 3 of the License, 
 *   or (at your option) any later version.
 * 
 *   JJazzLab is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU Lesser General Public License for more details.
 *  
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with JJazzLab.  If not, see <https://www.gnu.org/licenses/>
 *  
 *   Contributor(s): 
 * 
 */
package org.jjazz.jjswing;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import org.jjazz.jjswing.bass.BassGeneratorSettings;
import org.jjazz.rhythm.api.rhythmparameters.RP_SYS_Marker;
import org.jjazz.song.api.Song;
import org.jjazz.uiutilities.api.UIUtilities;
import org.openide.util.Utilities;
import org.openide.windows.WindowManager;

/**
 * Advanced user settings for the jjSwing rhythms.
 */
public class AdvancedSettingsDialog extends JDialog
{

    private static final Logger LOGGER = Logger.getLogger(AdvancedSettingsDialog.class.getName());

    public AdvancedSettingsDialog()
    {
        super(WindowManager.getDefault().getMainWindow(), false);

        initComponents();

        UIUtilities.installEnterKeyAction(this, () -> btn_okActionPerformed(null));
        UIUtilities.installEscapeKeyAction(this, () -> btn_okActionPerformed(null));

        var settings = BassGeneratorSettings.getInstance();
        settings.addPropertyChangeListener(e -> modelChanged());

        modelChanged();

        pack();

        setLocationRelativeTo(WindowManager.getDefault().getMainWindow());
    }

    // =================================================================================================================
    // Private methods
    // =================================================================================================================

    /**
     * Hack to trigger a change so music is regenerated
     */
    private void triggerCurrentSongChange()
    {
        Song song = Utilities.actionsGlobalContext().lookup(Song.class);
        if (song == null)
        {
            return;
        }
        var sgs = song.getSongStructure();
        var spts = sgs.getSongParts();
        if (spts.isEmpty() || !spts.getFirst().getRhythm().getUniqueId().equals("jjSwing-ID"))
        {
            return;
        }
        LOGGER.log(Level.SEVERE, "Generating dummy change in {0}", song);
        var spt = spts.getFirst();
        var r = spt.getRhythm();
        var rpMarker = RP_SYS_Marker.getMarkerRp(r);
        var rpValue = spt.getRPValue(rpMarker);
        rpValue = rpMarker.getNextValue(rpValue);
        sgs.setRhythmParameterValue(spt, rpMarker, rpValue);
    }

    private void modelChanged()
    {
        var settings = BassGeneratorSettings.getInstance();
        float newIntensity = settings.getSwingProfileIntensity();
        if (newIntensity != readIntensity())
        {
            cmb_swingProfileIntensity.setSelectedItem(String.valueOf(newIntensity));
        }
        triggerCurrentSongChange();
    }

    private float readIntensity()
    {
        String strIntensity = (String) cmb_swingProfileIntensity.getSelectedItem();
        return Float.parseFloat(strIntensity);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        cmb_swingProfileIntensity = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btn_ok = new javax.swing.JButton();

        setTitle("jjSwing advanced settings"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Swing-feel tempo adaptation"));

        cmb_swingProfileIntensity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.0", "1.0", "2.0" }));
        cmb_swingProfileIntensity.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmb_swingProfileIntensityActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, "Swing feel adaptation intensity"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmb_swingProfileIntensity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(196, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_swingProfileIntensity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        org.openide.awt.Mnemonics.setLocalizedText(btn_ok, "OK"); // NOI18N
        btn_ok.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_ok)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ok)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_okActionPerformed
    {//GEN-HEADEREND:event_btn_okActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btn_okActionPerformed

    private void cmb_swingProfileIntensityActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmb_swingProfileIntensityActionPerformed
    {//GEN-HEADEREND:event_cmb_swingProfileIntensityActionPerformed
        BassGeneratorSettings.getInstance().setSwingProfileIntensity(readIntensity());
    }//GEN-LAST:event_cmb_swingProfileIntensityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ok;
    private javax.swing.JComboBox<String> cmb_swingProfileIntensity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables


}
