/*
 *  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 * 
 *  Copyright @2019 Jerome Lelasseux. All rights reserved.
 *
 *  This file is part of the JJazzLab software.
 *   
 *  JJazzLab is free software: you can redistribute it and/or modify
 *  it under the terms of the Lesser GNU General Public License (LGPLv3) 
 *  as published by the Free Software Foundation, either version 3 of the License, 
 *  or (at your option) any later version.
 *
 *  JJazzLab is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
 *  GNU Lesser General Public License for more details.
 * 
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with JJazzLab.  If not, see <https://www.gnu.org/licenses/>
 * 
 *  Contributor(s): 
 */
package org.jjazz.rpcustomeditorfactoryimpl;

import static com.google.common.base.Preconditions.checkNotNull;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import org.jjazz.phrasetransform.api.PtProperties;
import org.jjazz.flatcomponents.api.FlatIntegerKnob;
import org.jjazz.uiutilities.api.UIUtilities;
import org.openide.windows.WindowManager;

/**
 * A generic dialog to edit a single property setting of a PhraseTransform.
 */
public class PtSinglePropertyEditor extends javax.swing.JDialog implements PropertyChangeListener
{

    private final PtProperties ptProperties;
    private final String property;
    private final String displayName;


    /**
     * 
     * @param ptProperties The properties we modify
     * @param dialogTitle 
     * @param property The proprerty name we read/write
     * @param propertyDisplayName The display name of the property
     * @param minPropertyValue 
     * @param maxPropertyValue
     * @param usePanoramicKnob 
     */
    public PtSinglePropertyEditor(PtProperties ptProperties, String dialogTitle, String property, String propertyDisplayName, int minPropertyValue, int maxPropertyValue, boolean usePanoramicKnob)
    {
        super(WindowManager.getDefault().getMainWindow(), true);
        checkNotNull(ptProperties);
        checkNotNull(property);
        checkNotNull(propertyDisplayName);

        this.displayName = propertyDisplayName;

        initComponents();

        this.ptProperties = ptProperties;
        knob.setPanoramicType(usePanoramicKnob);
        knob.setMinValue(minPropertyValue);
        knob.setMaxValue(maxPropertyValue);
        knob.setValue(ptProperties.getPropertyAsInteger(property));
        this.property = property;

        UIUtilities.installEnterKeyAction(this, () -> exit());
        UIUtilities.installEscapeKeyAction(this, () -> exit());
        
        knob.addPropertyChangeListener(this);        
        pnl_main.setToolTipText(dialogTitle);
    }

    @Override
    public void propertyChange(PropertyChangeEvent evt)
    {
        if (evt.getSource() == knob)
        {
            if (evt.getPropertyName().equals(FlatIntegerKnob.PROP_VALUE))
            {
                ptProperties.setProperty(property, knob.getValue());
            }
        }
    }

    private void exit()
    {
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
     * this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pnl_main = new javax.swing.JPanel();
        fbtn_close = new org.jjazz.flatcomponents.api.FlatButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        knob = new org.jjazz.flatcomponents.api.FlatIntegerKnob();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        lbl_name = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        pnl_main.setBackground(getBackground().darker());
        pnl_main.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        fbtn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jjazz/phrasetransform/resources/Close-10x10.png"))); // NOI18N
        fbtn_close.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                fbtn_closeActionPerformed(evt);
            }
        });

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        knob.setKnobRadius(10.0);
        knob.setOpaque(false);
        knob.setValueLineColor(new java.awt.Color(255, 153, 51));
        knob.setValueLineGap(1.5);

        javax.swing.GroupLayout knobLayout = new javax.swing.GroupLayout(knob);
        knob.setLayout(knobLayout);
        knobLayout.setHorizontalGroup(
            knobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );
        knobLayout.setVerticalGroup(
            knobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(knob);
        jPanel1.add(filler1);

        lbl_name.setFont(lbl_name.getFont().deriveFont(lbl_name.getFont().getSize()-1f));
        org.openide.awt.Mnemonics.setLocalizedText(lbl_name, displayName);
        lbl_name.setAlignmentX(0.5F);
        jPanel1.add(lbl_name);

        jPanel2.add(jPanel1);

        javax.swing.GroupLayout pnl_mainLayout = new javax.swing.GroupLayout(pnl_main);
        pnl_main.setLayout(pnl_mainLayout);
        pnl_mainLayout.setHorizontalGroup(
            pnl_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_mainLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fbtn_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_mainLayout.setVerticalGroup(
            pnl_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_mainLayout.createSequentialGroup()
                .addComponent(fbtn_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_main, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fbtn_closeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_fbtn_closeActionPerformed
    {//GEN-HEADEREND:event_fbtn_closeActionPerformed
        exit();
    }//GEN-LAST:event_fbtn_closeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jjazz.flatcomponents.api.FlatButton fbtn_close;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.jjazz.flatcomponents.api.FlatIntegerKnob knob;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JPanel pnl_main;
    // End of variables declaration//GEN-END:variables


}
