/*
 *  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 * 
 *  Copyright @2019 Jerome Lelasseux. All rights reserved.
 *
 *  This file is part of the JJazzLabX software.
 *   
 *  JJazzLabX is free software: you can redistribute it and/or modify
 *  it under the terms of the Lesser GNU General Public License (LGPLv3) 
 *  as published by the Free Software Foundation, either version 3 of the License, 
 *  or (at your option) any later version.
 *
 *  JJazzLabX is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
 *  GNU Lesser General Public License for more details.
 * 
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with JJazzLabX.  If not, see <https://www.gnu.org/licenses/>
 * 
 *  Contributor(s): 
 */
package org.jjazz.pianoroll;

import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.LayoutManager;
import org.jjazz.pianoroll.api.PianoRollEditor;
import org.jjazz.ui.keyboardcomponent.api.KeyboardComponent;
import org.jjazz.ui.keyboardcomponent.api.KeyboardComponent.Orientation;
import org.jjazz.ui.keyboardcomponent.api.KeyboardRange;

/**
 * The panel representing the ruler, the keyboard on the left, and the notes on the right.
 */
public class KeysAndNotesPanel extends javax.swing.JPanel
{

    NotesPanel notesPanel;
    KeyboardComponent keyboard;

    private final PianoRollEditor editor;

    /**
     * Creates new form PianoRollPanel
     */
    public KeysAndNotesPanel(PianoRollEditor editor)
    {
        this.editor = editor;
        this.keyboard = new KeyboardComponent(KeyboardRange._128_KEYS, Orientation.RIGHT, false);
        notesPanel = new NotesPanel(editor, keyboard);

        initComponents();
        
        pnl_keynotes.setLayout(new MyLayoutManager());        
        addNotesText(kbd);
        pnl_notes.add(notesPanel);


    }

    /**
     * @param factor A value &gt; 0
     */
    public void setZoomY(float factor)
    {
        kbd.setScaleFactor(factor, Math.min(1.5f, factor));
        // kbd.setScaleFactor(factor, factor);
    }

    // ==========================================================================================================
    // Private methods
    // ==========================================================================================================    
    private void addNotesText(KeyboardComponent kbd)
    {
        for (var key : kbd.getWhiteKeys())
        {
            int p = key.getPitch();
            if (p % 12 == 0)
            {
                int o = p / 12 - 1;
                key.setText("C" + o);
            }
        }
    }

    // ==========================================================================================================
    // Inner classes
    // ==========================================================================================================    

    /**
     * A simple LayoutManager for keyboard + notesPanel.
     * <p>
     * Layout the keyboard on the left at preferred size. NotesPanel reuses the same height than keyboard.
     */
    private class MyLayoutManager implements LayoutManager
    {

        @Override
        public void addLayoutComponent(String name, Component comp)
        {
            assert comp == keyboard || comp == notesPanel;
        }

        @Override
        public void removeLayoutComponent(Component comp)
        {
            // 
        }

        @Override
        public Dimension preferredLayoutSize(Container parent)
        {
            return new Dimension(keyboard.getPreferredSize().width + notesPanel.getPreferredSize().width, keyboard.getPreferredSize().height);
        }

        @Override
        public Dimension minimumLayoutSize(Container parent)
        {
            return new Dimension(keyboard.getMinimumSize().width + notesPanel.getMinimumSize().width, keyboard.getMinimumSize().height);
        }

        @Override
        public void layoutContainer(Container parent)
        {
            assert parent == pnl_keynotes;
            keyboard.setLocation(0, 0);
            keyboard.setSize(keyboard.getPreferredSize());
            notesPanel.setLocation(keyboard.getWidth(), 0);
            notesPanel.setSize(notesPanel.getPreferredSize().width, keyboard.getHeight());
        }

    }


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
     * this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pnl_ruler = new RulerPanel(editor, notesPanel);
        scrollPane_keysAndNotes = new javax.swing.JScrollPane();
        pnl_keynotes = new javax.swing.JPanel();
        kbd = keyboard;
        pnl_notes = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pnl_rulerLayout = new javax.swing.GroupLayout(pnl_ruler);
        pnl_ruler.setLayout(pnl_rulerLayout);
        pnl_rulerLayout.setHorizontalGroup(
            pnl_rulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 998, Short.MAX_VALUE)
        );
        pnl_rulerLayout.setVerticalGroup(
            pnl_rulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        add(pnl_ruler, java.awt.BorderLayout.NORTH);

        pnl_keynotes.setLayout(new javax.swing.BoxLayout(pnl_keynotes, javax.swing.BoxLayout.X_AXIS));
        pnl_keynotes.add(kbd);

        pnl_notes.setLayout(new javax.swing.BoxLayout(pnl_notes, javax.swing.BoxLayout.LINE_AXIS));
        pnl_keynotes.add(pnl_notes);

        scrollPane_keysAndNotes.setViewportView(pnl_keynotes);

        add(scrollPane_keysAndNotes, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jjazz.ui.keyboardcomponent.api.KeyboardComponent kbd;
    private javax.swing.JPanel pnl_keynotes;
    private javax.swing.JPanel pnl_notes;
    private javax.swing.JPanel pnl_ruler;
    private javax.swing.JScrollPane scrollPane_keysAndNotes;
    // End of variables declaration//GEN-END:variables


}
