// Generated by jextract

package org.javafluidsynth.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$50 {

    static final FunctionDescriptor fluid_midi_event_get_channel$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle fluid_midi_event_get_channel$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_midi_event_get_channel",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$50.fluid_midi_event_get_channel$FUNC, false
    );
    static final FunctionDescriptor fluid_midi_event_get_key$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle fluid_midi_event_get_key$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_midi_event_get_key",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$50.fluid_midi_event_get_key$FUNC, false
    );
    static final FunctionDescriptor fluid_midi_event_set_key$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT
    );
    static final MethodHandle fluid_midi_event_set_key$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_midi_event_set_key",
        "(Ljdk/incubator/foreign/MemoryAddress;I)I",
        constants$50.fluid_midi_event_set_key$FUNC, false
    );
    static final FunctionDescriptor fluid_midi_event_get_velocity$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle fluid_midi_event_get_velocity$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_midi_event_get_velocity",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$50.fluid_midi_event_get_velocity$FUNC, false
    );
    static final FunctionDescriptor fluid_midi_event_set_velocity$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT
    );
    static final MethodHandle fluid_midi_event_set_velocity$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_midi_event_set_velocity",
        "(Ljdk/incubator/foreign/MemoryAddress;I)I",
        constants$50.fluid_midi_event_set_velocity$FUNC, false
    );
    static final FunctionDescriptor fluid_midi_event_get_control$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle fluid_midi_event_get_control$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_midi_event_get_control",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$50.fluid_midi_event_get_control$FUNC, false
    );
}


