// Generated by jextract

package org.javafluidsynth.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$19 {

    static final FunctionDescriptor fluid_synth_count_audio_groups$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle fluid_synth_count_audio_groups$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_count_audio_groups",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$19.fluid_synth_count_audio_groups$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_count_effects_channels$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle fluid_synth_count_effects_channels$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_count_effects_channels",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$19.fluid_synth_count_effects_channels$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_count_effects_groups$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle fluid_synth_count_effects_groups$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_count_effects_groups",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$19.fluid_synth_count_effects_groups$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_set_sample_rate$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_FLOAT
    );
    static final MethodHandle fluid_synth_set_sample_rate$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_set_sample_rate",
        "(Ljdk/incubator/foreign/MemoryAddress;F)V",
        constants$19.fluid_synth_set_sample_rate$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_set_gain$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_FLOAT
    );
    static final MethodHandle fluid_synth_set_gain$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_set_gain",
        "(Ljdk/incubator/foreign/MemoryAddress;F)V",
        constants$19.fluid_synth_set_gain$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_get_gain$FUNC = FunctionDescriptor.of(C_FLOAT,
        C_POINTER
    );
    static final MethodHandle fluid_synth_get_gain$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_get_gain",
        "(Ljdk/incubator/foreign/MemoryAddress;)F",
        constants$19.fluid_synth_get_gain$FUNC, false
    );
}


