// Generated by jextract

package org.javafluidsynth.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$11 {

    static final FunctionDescriptor fluid_synth_get_sfont_by_id$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_INT
    );
    static final MethodHandle fluid_synth_get_sfont_by_id$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_get_sfont_by_id",
        "(Ljdk/incubator/foreign/MemoryAddress;I)Ljdk/incubator/foreign/MemoryAddress;",
        constants$11.fluid_synth_get_sfont_by_id$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_get_sfont_by_name$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle fluid_synth_get_sfont_by_name$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_get_sfont_by_name",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$11.fluid_synth_get_sfont_by_name$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_set_bank_offset$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_INT
    );
    static final MethodHandle fluid_synth_set_bank_offset$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_set_bank_offset",
        "(Ljdk/incubator/foreign/MemoryAddress;II)I",
        constants$11.fluid_synth_set_bank_offset$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_get_bank_offset$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT
    );
    static final MethodHandle fluid_synth_get_bank_offset$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_get_bank_offset",
        "(Ljdk/incubator/foreign/MemoryAddress;I)I",
        constants$11.fluid_synth_get_bank_offset$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_set_reverb_on$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_INT
    );
    static final MethodHandle fluid_synth_set_reverb_on$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_set_reverb_on",
        "(Ljdk/incubator/foreign/MemoryAddress;I)V",
        constants$11.fluid_synth_set_reverb_on$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_reverb_on$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_INT
    );
    static final MethodHandle fluid_synth_reverb_on$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_reverb_on",
        "(Ljdk/incubator/foreign/MemoryAddress;II)I",
        constants$11.fluid_synth_reverb_on$FUNC, false
    );
}


