// Generated by jextract

package org.javafluidsynth.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$25 {

    static final FunctionDescriptor fluid_synth_get_settings$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle fluid_synth_get_settings$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_get_settings",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$25.fluid_synth_get_settings$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_add_sfloader$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle fluid_synth_add_sfloader$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_add_sfloader",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$25.fluid_synth_add_sfloader$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_get_channel_preset$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_INT
    );
    static final MethodHandle fluid_synth_get_channel_preset$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_get_channel_preset",
        "(Ljdk/incubator/foreign/MemoryAddress;I)Ljdk/incubator/foreign/MemoryAddress;",
        constants$25.fluid_synth_get_channel_preset$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_handle_midi_event$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle fluid_synth_handle_midi_event$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_handle_midi_event",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$25.fluid_synth_handle_midi_event$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_pin_preset$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle fluid_synth_pin_preset$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_pin_preset",
        "(Ljdk/incubator/foreign/MemoryAddress;III)I",
        constants$25.fluid_synth_pin_preset$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_unpin_preset$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle fluid_synth_unpin_preset$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_unpin_preset",
        "(Ljdk/incubator/foreign/MemoryAddress;III)I",
        constants$25.fluid_synth_unpin_preset$FUNC, false
    );
}


