// Generated by jextract

package org.javafluidsynth.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$10 {

    static final FunctionDescriptor fluid_synth_sfreload$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT
    );
    static final MethodHandle fluid_synth_sfreload$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_sfreload",
        "(Ljdk/incubator/foreign/MemoryAddress;I)I",
        constants$10.fluid_synth_sfreload$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_sfunload$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_INT
    );
    static final MethodHandle fluid_synth_sfunload$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_sfunload",
        "(Ljdk/incubator/foreign/MemoryAddress;II)I",
        constants$10.fluid_synth_sfunload$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_add_sfont$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle fluid_synth_add_sfont$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_add_sfont",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$10.fluid_synth_add_sfont$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_remove_sfont$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle fluid_synth_remove_sfont$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_remove_sfont",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$10.fluid_synth_remove_sfont$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_sfcount$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle fluid_synth_sfcount$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_sfcount",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$10.fluid_synth_sfcount$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_get_sfont$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_INT
    );
    static final MethodHandle fluid_synth_get_sfont$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_get_sfont",
        "(Ljdk/incubator/foreign/MemoryAddress;I)Ljdk/incubator/foreign/MemoryAddress;",
        constants$10.fluid_synth_get_sfont$FUNC, false
    );
}


