// Generated by jextract

package org.javafluidsynth.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$34 {

    static final FunctionDescriptor new_fluid_sfont$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle new_fluid_sfont$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "new_fluid_sfont",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$34.new_fluid_sfont$FUNC, false
    );
    static final FunctionDescriptor delete_fluid_sfont$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle delete_fluid_sfont$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "delete_fluid_sfont",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$34.delete_fluid_sfont$FUNC, false
    );
    static final FunctionDescriptor fluid_sfont_set_data$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle fluid_sfont_set_data$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_sfont_set_data",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$34.fluid_sfont_set_data$FUNC, false
    );
    static final FunctionDescriptor fluid_sfont_get_data$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle fluid_sfont_get_data$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_sfont_get_data",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$34.fluid_sfont_get_data$FUNC, false
    );
    static final FunctionDescriptor fluid_sfont_get_id$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle fluid_sfont_get_id$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_sfont_get_id",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$34.fluid_sfont_get_id$FUNC, false
    );
    static final FunctionDescriptor fluid_sfont_get_name$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle fluid_sfont_get_name$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_sfont_get_name",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$34.fluid_sfont_get_name$FUNC, false
    );
}


