// Generated by jextract

package org.javafluidsynth.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$13 {

    static final FunctionDescriptor fluid_synth_get_reverb_damp$FUNC = FunctionDescriptor.of(C_DOUBLE,
        C_POINTER
    );
    static final MethodHandle fluid_synth_get_reverb_damp$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_get_reverb_damp",
        "(Ljdk/incubator/foreign/MemoryAddress;)D",
        constants$13.fluid_synth_get_reverb_damp$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_get_reverb_level$FUNC = FunctionDescriptor.of(C_DOUBLE,
        C_POINTER
    );
    static final MethodHandle fluid_synth_get_reverb_level$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_get_reverb_level",
        "(Ljdk/incubator/foreign/MemoryAddress;)D",
        constants$13.fluid_synth_get_reverb_level$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_get_reverb_width$FUNC = FunctionDescriptor.of(C_DOUBLE,
        C_POINTER
    );
    static final MethodHandle fluid_synth_get_reverb_width$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_get_reverb_width",
        "(Ljdk/incubator/foreign/MemoryAddress;)D",
        constants$13.fluid_synth_get_reverb_width$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_set_reverb_group_roomsize$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_DOUBLE
    );
    static final MethodHandle fluid_synth_set_reverb_group_roomsize$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_set_reverb_group_roomsize",
        "(Ljdk/incubator/foreign/MemoryAddress;ID)I",
        constants$13.fluid_synth_set_reverb_group_roomsize$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_set_reverb_group_damp$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_DOUBLE
    );
    static final MethodHandle fluid_synth_set_reverb_group_damp$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_set_reverb_group_damp",
        "(Ljdk/incubator/foreign/MemoryAddress;ID)I",
        constants$13.fluid_synth_set_reverb_group_damp$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_set_reverb_group_width$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_DOUBLE
    );
    static final MethodHandle fluid_synth_set_reverb_group_width$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_set_reverb_group_width",
        "(Ljdk/incubator/foreign/MemoryAddress;ID)I",
        constants$13.fluid_synth_set_reverb_group_width$FUNC, false
    );
}


