// Generated by jextract

package org.javafluidsynth.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$6 {

    static final FunctionDescriptor fluid_synth_get_pitch_bend$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_POINTER
    );
    static final MethodHandle fluid_synth_get_pitch_bend$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_get_pitch_bend",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I",
        constants$6.fluid_synth_get_pitch_bend$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_pitch_wheel_sens$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_INT
    );
    static final MethodHandle fluid_synth_pitch_wheel_sens$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_pitch_wheel_sens",
        "(Ljdk/incubator/foreign/MemoryAddress;II)I",
        constants$6.fluid_synth_pitch_wheel_sens$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_get_pitch_wheel_sens$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_POINTER
    );
    static final MethodHandle fluid_synth_get_pitch_wheel_sens$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_get_pitch_wheel_sens",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I",
        constants$6.fluid_synth_get_pitch_wheel_sens$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_program_change$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_INT
    );
    static final MethodHandle fluid_synth_program_change$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_program_change",
        "(Ljdk/incubator/foreign/MemoryAddress;II)I",
        constants$6.fluid_synth_program_change$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_channel_pressure$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_INT
    );
    static final MethodHandle fluid_synth_channel_pressure$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_channel_pressure",
        "(Ljdk/incubator/foreign/MemoryAddress;II)I",
        constants$6.fluid_synth_channel_pressure$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_key_pressure$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle fluid_synth_key_pressure$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_key_pressure",
        "(Ljdk/incubator/foreign/MemoryAddress;III)I",
        constants$6.fluid_synth_key_pressure$FUNC, false
    );
}


