// Generated by jextract

package org.javafluidsynth.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$14 {

    static final FunctionDescriptor fluid_synth_set_reverb_group_level$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_DOUBLE
    );
    static final MethodHandle fluid_synth_set_reverb_group_level$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_set_reverb_group_level",
        "(Ljdk/incubator/foreign/MemoryAddress;ID)I",
        constants$14.fluid_synth_set_reverb_group_level$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_get_reverb_group_roomsize$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_POINTER
    );
    static final MethodHandle fluid_synth_get_reverb_group_roomsize$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_get_reverb_group_roomsize",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I",
        constants$14.fluid_synth_get_reverb_group_roomsize$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_get_reverb_group_damp$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_POINTER
    );
    static final MethodHandle fluid_synth_get_reverb_group_damp$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_get_reverb_group_damp",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I",
        constants$14.fluid_synth_get_reverb_group_damp$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_get_reverb_group_width$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_POINTER
    );
    static final MethodHandle fluid_synth_get_reverb_group_width$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_get_reverb_group_width",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I",
        constants$14.fluid_synth_get_reverb_group_width$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_get_reverb_group_level$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_POINTER
    );
    static final MethodHandle fluid_synth_get_reverb_group_level$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_get_reverb_group_level",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I",
        constants$14.fluid_synth_get_reverb_group_level$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_set_chorus_on$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_INT
    );
    static final MethodHandle fluid_synth_set_chorus_on$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_set_chorus_on",
        "(Ljdk/incubator/foreign/MemoryAddress;I)V",
        constants$14.fluid_synth_set_chorus_on$FUNC, false
    );
}


