// Generated by jextract

package org.javafluidsynth.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$0 {

    static final FunctionDescriptor new_fluid_settings$FUNC = FunctionDescriptor.of(C_POINTER);
    static final MethodHandle new_fluid_settings$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "new_fluid_settings",
        "()Ljdk/incubator/foreign/MemoryAddress;",
        constants$0.new_fluid_settings$FUNC, false
    );
    static final FunctionDescriptor delete_fluid_settings$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle delete_fluid_settings$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "delete_fluid_settings",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$0.delete_fluid_settings$FUNC, false
    );
    static final FunctionDescriptor fluid_settings_get_type$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle fluid_settings_get_type$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_settings_get_type",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$0.fluid_settings_get_type$FUNC, false
    );
    static final FunctionDescriptor fluid_settings_get_hints$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle fluid_settings_get_hints$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_settings_get_hints",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$0.fluid_settings_get_hints$FUNC, false
    );
    static final FunctionDescriptor fluid_settings_is_realtime$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle fluid_settings_is_realtime$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_settings_is_realtime",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$0.fluid_settings_is_realtime$FUNC, false
    );
    static final FunctionDescriptor fluid_settings_setstr$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle fluid_settings_setstr$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_settings_setstr",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$0.fluid_settings_setstr$FUNC, false
    );
}


