// Generated by jextract

package org.javafluidsynth.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$43 {

    static final FunctionDescriptor fluid_event_bank_select$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_INT,
        C_SHORT
    );
    static final MethodHandle fluid_event_bank_select$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_event_bank_select",
        "(Ljdk/incubator/foreign/MemoryAddress;IS)V",
        constants$43.fluid_event_bank_select$FUNC, false
    );
    static final FunctionDescriptor fluid_event_program_change$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_INT,
        C_INT
    );
    static final MethodHandle fluid_event_program_change$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_event_program_change",
        "(Ljdk/incubator/foreign/MemoryAddress;II)V",
        constants$43.fluid_event_program_change$FUNC, false
    );
    static final FunctionDescriptor fluid_event_program_select$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_INT,
        C_INT,
        C_SHORT,
        C_SHORT
    );
    static final MethodHandle fluid_event_program_select$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_event_program_select",
        "(Ljdk/incubator/foreign/MemoryAddress;IISS)V",
        constants$43.fluid_event_program_select$FUNC, false
    );
    static final FunctionDescriptor fluid_event_control_change$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_INT,
        C_SHORT,
        C_INT
    );
    static final MethodHandle fluid_event_control_change$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_event_control_change",
        "(Ljdk/incubator/foreign/MemoryAddress;ISI)V",
        constants$43.fluid_event_control_change$FUNC, false
    );
    static final FunctionDescriptor fluid_event_pitch_bend$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_INT,
        C_INT
    );
    static final MethodHandle fluid_event_pitch_bend$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_event_pitch_bend",
        "(Ljdk/incubator/foreign/MemoryAddress;II)V",
        constants$43.fluid_event_pitch_bend$FUNC, false
    );
    static final FunctionDescriptor fluid_event_pitch_wheelsens$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_INT,
        C_INT
    );
    static final MethodHandle fluid_event_pitch_wheelsens$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_event_pitch_wheelsens",
        "(Ljdk/incubator/foreign/MemoryAddress;II)V",
        constants$43.fluid_event_pitch_wheelsens$FUNC, false
    );
}


