// Generated by jextract

package org.javafluidsynth.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$7 {

    static final FunctionDescriptor fluid_synth_bank_select$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_INT
    );
    static final MethodHandle fluid_synth_bank_select$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_bank_select",
        "(Ljdk/incubator/foreign/MemoryAddress;II)I",
        constants$7.fluid_synth_bank_select$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_sfont_select$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_INT
    );
    static final MethodHandle fluid_synth_sfont_select$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_sfont_select",
        "(Ljdk/incubator/foreign/MemoryAddress;II)I",
        constants$7.fluid_synth_sfont_select$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_program_select$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle fluid_synth_program_select$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_program_select",
        "(Ljdk/incubator/foreign/MemoryAddress;IIII)I",
        constants$7.fluid_synth_program_select$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_program_select_by_sfont_name$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_POINTER,
        C_INT,
        C_INT
    );
    static final MethodHandle fluid_synth_program_select_by_sfont_name$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_program_select_by_sfont_name",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;II)I",
        constants$7.fluid_synth_program_select_by_sfont_name$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_get_program$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle fluid_synth_get_program$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_get_program",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$7.fluid_synth_get_program$FUNC, false
    );
    static final FunctionDescriptor fluid_synth_unset_program$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT
    );
    static final MethodHandle fluid_synth_unset_program$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_synth_unset_program",
        "(Ljdk/incubator/foreign/MemoryAddress;I)I",
        constants$7.fluid_synth_unset_program$FUNC, false
    );
}


