// Generated by jextract

package org.javafluidsynth.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$47 {

    static final FunctionDescriptor fluid_event_get_control$FUNC = FunctionDescriptor.of(C_SHORT,
        C_POINTER
    );
    static final MethodHandle fluid_event_get_control$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_event_get_control",
        "(Ljdk/incubator/foreign/MemoryAddress;)S",
        constants$47.fluid_event_get_control$FUNC, false
    );
    static final FunctionDescriptor fluid_event_get_value$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle fluid_event_get_value$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_event_get_value",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$47.fluid_event_get_value$FUNC, false
    );
    static final FunctionDescriptor fluid_event_get_program$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle fluid_event_get_program$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_event_get_program",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$47.fluid_event_get_program$FUNC, false
    );
    static final FunctionDescriptor fluid_event_get_data$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle fluid_event_get_data$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_event_get_data",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$47.fluid_event_get_data$FUNC, false
    );
    static final FunctionDescriptor fluid_event_get_duration$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle fluid_event_get_duration$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_event_get_duration",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$47.fluid_event_get_duration$FUNC, false
    );
    static final FunctionDescriptor fluid_event_get_bank$FUNC = FunctionDescriptor.of(C_SHORT,
        C_POINTER
    );
    static final MethodHandle fluid_event_get_bank$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_event_get_bank",
        "(Ljdk/incubator/foreign/MemoryAddress;)S",
        constants$47.fluid_event_get_bank$FUNC, false
    );
}


