// Generated by jextract

package org.javafluidsynth.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$53 {

    static final FunctionDescriptor new_fluid_midi_router$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle new_fluid_midi_router$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "new_fluid_midi_router",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$53.new_fluid_midi_router$FUNC, false
    );
    static final FunctionDescriptor delete_fluid_midi_router$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle delete_fluid_midi_router$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "delete_fluid_midi_router",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$53.delete_fluid_midi_router$FUNC, false
    );
    static final FunctionDescriptor fluid_midi_router_set_default_rules$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle fluid_midi_router_set_default_rules$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_midi_router_set_default_rules",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$53.fluid_midi_router_set_default_rules$FUNC, false
    );
    static final FunctionDescriptor fluid_midi_router_clear_rules$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle fluid_midi_router_clear_rules$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_midi_router_clear_rules",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$53.fluid_midi_router_clear_rules$FUNC, false
    );
    static final FunctionDescriptor fluid_midi_router_add_rule$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_INT
    );
    static final MethodHandle fluid_midi_router_add_rule$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "fluid_midi_router_add_rule",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;I)I",
        constants$53.fluid_midi_router_add_rule$FUNC, false
    );
    static final FunctionDescriptor new_fluid_midi_router_rule$FUNC = FunctionDescriptor.of(C_POINTER);
    static final MethodHandle new_fluid_midi_router_rule$MH = RuntimeHelper.downcallHandle(
        fluidsynth_h.LIBRARIES, "new_fluid_midi_router_rule",
        "()Ljdk/incubator/foreign/MemoryAddress;",
        constants$53.new_fluid_midi_router_rule$FUNC, false
    );
}


