/*
 *  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 * 
 *  Copyright @2019 Jerome Lelasseux. All rights reserved.
 *
 *  This file is part of the JJazzLabX software.
 *   
 *  JJazzLabX is free software: you can redistribute it and/or modify
 *  it under the terms of the Lesser GNU General Public License (LGPLv3) 
 *  as published by the Free Software Foundation, either version 3 of the License, 
 *  or (at your option) any later version.
 *
 *  JJazzLabX is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 * 
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with JJazzLabX.  If not, see <https://www.gnu.org/licenses/>
 * 
 *  Contributor(s): 
 */
package org.jjazz.ui.spteditor.api;

import java.awt.Dimension;
import org.jjazz.ui.spteditor.SptEditor;
import org.openide.awt.UndoRedo;
import org.openide.util.Lookup;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;
import static org.jjazz.ui.spteditor.api.Bundle.*;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.windows.WindowManager;

@ConvertAsProperties(
        dtd = "-//org.jjazz.ui.spteditor.api//SptEditorTopComponent//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "SptEditorTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "explorer", openAtStartup = true, position = 200)
@ActionID(category = "Window", id = "org.jjazz.ui.spteditor.api.SptEditorTopComponent")
// @ActionReference(path = "Menu/Window", position = 130)     useless if not closable
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_SptEditorAction",
        preferredID = "SptEditorTopComponent"
)
@Messages(
        {
            "CTL_SptEditorAction=Song Part Editor",
            "CTL_SptEditorTopComponent=Song Part",
            "HINT_SptEditorTopComponent=Edit parameters of the selected Song Parts"
        })
/**
 * A TopComponent to edit one SongPart.
 * <p>
 * TopComponent's lookup is the SptEditor's lookup.
 */
public final class SptEditorTopComponent extends TopComponent
{

    private SptEditor sptEditor;

    public SptEditorTopComponent()
    {
        setName(CTL_SptEditorTopComponent());
        setToolTipText(HINT_SptEditorTopComponent());
        putClientProperty(TopComponent.PROP_MAXIMIZATION_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_KEEP_PREFERRED_SIZE_WHEN_SLIDED_IN, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_DND_COPY_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_DRAGGING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_UNDOCKING_DISABLED, Boolean.FALSE);
        putClientProperty(TopComponent.PROP_SLIDING_DISABLED, Boolean.FALSE);

        initComponents();

        sptEditor = new SptEditor();
        sptEditor.setPreferredSize(new Dimension(80, 100));
        add(sptEditor);

    }

    /**
     * When UI is ready there is normally one unique instance of this TopComponent, which is not closable.
     *
     * @return
     */
    static public SptEditorTopComponent getInstance()
    {
        return (SptEditorTopComponent) WindowManager.getDefault().findTopComponent("SptEditorTopComponent");
    }

    @Override
    public void componentDeactivated()
    {
        super.componentDeactivated();
    }

    /**
     * Override to proxy the undoManager of the sptEditor.
     *
     * @return
     */
    @Override
    public UndoRedo getUndoRedo()
    {
        return sptEditor.getUndoManager();
    }

    @Override
    public Lookup getLookup()
    {
        return sptEditor.getLookup();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
     * this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened()
    {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed()
    {
        sptEditor.cleanup();
    }

    void writeProperties(java.util.Properties p)
    {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p)
    {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
