/*
 *  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 * 
 *  Copyright @2019 Jerome Lelasseux. All rights reserved.
 *
 *  This file is part of the JJazzLabX software.
 *   
 *  JJazzLabX is free software: you can redistribute it and/or modify
 *  it under the terms of the Lesser GNU General Public License (LGPLv3) 
 *  as published by the Free Software Foundation, either version 3 of the License, 
 *  or (at your option) any later version.
 *
 *  JJazzLabX is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 * 
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with JJazzLabX.  If not, see <https://www.gnu.org/licenses/>
 * 
 *  Contributor(s): 
 */
package org.jjazz.ui.spteditor.api;

import java.awt.Dimension;
import java.util.List;
import org.jjazz.songstructure.api.SongPart;
import org.jjazz.ui.spteditor.spi.SptEditorFactory;
import org.jjazz.util.ResUtil;
import org.openide.awt.UndoRedo;
import org.openide.util.Lookup;
import org.openide.windows.TopComponent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.windows.WindowManager;

@ConvertAsProperties(
        dtd = "-//org.jjazz.ui.spteditor.api//SptEditorTopComponent//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "SptEditorTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "explorer", openAtStartup = true, position = 200)
@ActionID(category = "Window", id = "org.jjazz.ui.spteditor.api.SptEditorTopComponent")
// @ActionReference(path = "Menu/Window", position = 130)     useless if not closable
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_SptEditorAction",
        preferredID = "SptEditorTopComponent"
)
/**
 * A TopComponent to edit one or more SongParts.
 * <p>
 * TopComponent's lookup is the SptEditor's lookup.
 */
public final class SptEditorTopComponent extends TopComponent
{

    private SptEditor sptEditor;

    public SptEditorTopComponent()
    {
        setName(ResUtil.getString(getClass(), "CTL_SptEditorTopComponent"));
        setToolTipText(ResUtil.getString(getClass(), "CTL_SptEditorTopComponent"));
        putClientProperty(TopComponent.PROP_MAXIMIZATION_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_KEEP_PREFERRED_SIZE_WHEN_SLIDED_IN, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_DND_COPY_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_DRAGGING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_UNDOCKING_DISABLED, Boolean.FALSE);
        putClientProperty(TopComponent.PROP_SLIDING_DISABLED, Boolean.FALSE);

        initComponents();

        SptEditorFactory factory = SptEditorFactory.getDefault();
        sptEditor = factory.createEditor(factory.getDefaultSptEditorSettings(), factory.getDefaultRpEditorFactory());
        sptEditor.setPreferredSize(new Dimension(80, 100));
        add(sptEditor);


    }

    /**
     * When UI is ready there is normally one unique instance of this TopComponent, which is not closable.
     *
     * @return
     */
    static public SptEditorTopComponent getInstance()
    {
        return (SptEditorTopComponent) WindowManager.getDefault().findTopComponent("SptEditorTopComponent");
    }

    @Override
    public void componentDeactivated()
    {
        super.componentDeactivated();
    }

    /**
     * Override to proxy the undoManager of the sptEditor.
     *
     * @return
     */
    @Override
    public UndoRedo getUndoRedo()
    {
        return sptEditor.getUndoManager();
    }

    @Override
    public Lookup getLookup()
    {
        return sptEditor.getLookup();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
     * this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened()
    {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed()
    {
        sptEditor.cleanup();
    }

    void writeProperties(java.util.Properties p)
    {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p)
    {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    /**
     * Update the TopComponent tab name depending on the specified song parts.
     * <p>
     * @param spts The song parts
     */
    private void updateTabName(List<SongPart> spts)
    {
//        String tabName = ResUtil.getString(getClass(), "CTL_SongParts");
//        if (!spts.isEmpty())
//        {
//            SongPart spt0 = spts.get(0);
//            int spt0Index = songModel.getSongStructure().getSongParts().indexOf(spts.get(0));
//            if (spts.size() > 1)
//            {
//                String spt0Name = org.jjazz.util.Utilities.truncate(spt0.getName(), 4) + "(" + (spt0Index + 1) + ")";
//                SongPart lastSpt = spts.get(spts.size() - 1);
//                int lastSptIndex = songModel.getSongStructure().getSongParts().indexOf(lastSpt);
//                String lastSptName = org.jjazz.util.Utilities.truncate(lastSpt.getName(), 4) + "(" + (lastSptIndex + 1) + ")";
//                tabName += " " + spt0Name + "..." + lastSptName;
//            } else
//            {
//                tabName += " " + org.jjazz.util.Utilities.truncateWithDots(spt0.getName(), 10) + "(" + (spt0Index + 1) + ")";
//            }
//        }
//        setDisplayName(tabName);
    }
}

