/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright @2019 Jerome Lelasseux. All rights reserved.
 *
 * This file is part of the JJazzLab-X software.
 *
 * JJazzLab-X is free software: you can redistribute it and/or modify
 * it under the terms of the Lesser GNU General Public License (LGPLv3) 
 * as published by the Free Software Foundation, either version 3 of the License, 
 * or (at your option) any later version.
 *
 * JJazzLab-X is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with JJazzLab-X.  If not, see <https://www.gnu.org/licenses/>
 *
 * Contributor(s): 
 *
 */
package org.jjazz.outputsynth.ui;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.stream.Collectors;
import org.jjazz.outputsynth.OutputSynth;
import org.jjazz.outputsynth.OutputSynthManager;
import org.jjazz.util.Utilities;
import org.openide.awt.Actions;

/**
 *
 * @author Administrateur
 */
public class OutputSynthToolbarPanel extends javax.swing.JPanel implements PropertyChangeListener
{

    OutputSynth outputSynth;

    /**
     * Creates new form OutputSynthToolbarPanel
     */
    public OutputSynthToolbarPanel()
    {
        initComponents();
        this.fbtn_editOutputSynth.setAction(Actions.forID("OutputSynth", "org.jjazz.outputsynth.ui.editoutputsynth"));
        this.fbtn_playbackTransposition.setAction(Actions.forID("MusicControls", "org.jjazz.ui.musiccontrolactions.transposeplaybackkey"));

        var osm = OutputSynthManager.getInstance();
        osm.addPropertyChangeListener(this);

        outputSynth = osm.getOutputSynth();
        outputSynth.addPropertyChangeListener(this);

        updateLabels();
    }

    @Override
    public void propertyChange(PropertyChangeEvent evt)
    {
        var osm = OutputSynthManager.getInstance();
        if (evt.getSource() == osm
                && evt.getPropertyName().equals(OutputSynthManager.PROP_DEFAULT_OUTPUTSYNTH))
        {
            outputSynth.removePropertyChangeListener(this);
            outputSynth = osm.getOutputSynth();
            outputSynth.addPropertyChangeListener(this);
            updateLabels();
        } else if (evt.getSource() == outputSynth
                && (evt.getPropertyName().equals(OutputSynth.PROP_STD_BANK) || evt.getPropertyName().equals(OutputSynth.PROP_CUSTOM_SYNTH)))
        {
            updateLabels();
        }
    }

    private void updateLabels()
    {
        String strStdBanks = outputSynth.getCompatibleStdBanks().stream()
                .map(b -> b.getName())
                .collect(Collectors.toList()).toString().replace("[", "").replace("]", "").replace(" Bank", "");
        String strSynths = outputSynth.getCustomSynths().toString().replace("[", "").replace("]", "");
        strSynths = Utilities.truncateWithDots(strSynths, 60);
        lbl_stdBanks.setText(strStdBanks);
        lbl_synths.setText(strSynths);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
     * this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        fbtn_playbackTransposition = new org.jjazz.ui.flatcomponents.FlatButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        fbtn_editOutputSynth = new org.jjazz.ui.flatcomponents.FlatButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 32767));
        pnl_labels = new javax.swing.JPanel();
        lbl_stdBanks = new javax.swing.JLabel();
        lbl_synths = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
        add(filler1);

        fbtn_playbackTransposition.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jjazz/outputsynth/ui/resources/Sax-OFF-24x24.png"))); // NOI18N
        add(fbtn_playbackTransposition);
        add(filler3);

        fbtn_editOutputSynth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jjazz/outputsynth/ui/resources/OutputSynth2.png"))); // NOI18N
        fbtn_editOutputSynth.setToolTipText(org.openide.util.NbBundle.getMessage(OutputSynthToolbarPanel.class, "OutputSynthToolbarPanel.fbtn_editOutputSynth.toolTipText")); // NOI18N
        add(fbtn_editOutputSynth);
        add(filler2);

        pnl_labels.setLayout(new javax.swing.BoxLayout(pnl_labels, javax.swing.BoxLayout.Y_AXIS));

        lbl_stdBanks.setFont(lbl_stdBanks.getFont().deriveFont(lbl_stdBanks.getFont().getSize()-2f));
        org.openide.awt.Mnemonics.setLocalizedText(lbl_stdBanks, org.openide.util.NbBundle.getMessage(OutputSynthToolbarPanel.class, "OutputSynthToolbarPanel.lbl_stdBanks.text")); // NOI18N
        lbl_stdBanks.setToolTipText(org.openide.util.NbBundle.getMessage(OutputSynthToolbarPanel.class, "OutputSynthToolbarPanel.lbl_stdBanks.toolTipText")); // NOI18N
        pnl_labels.add(lbl_stdBanks);

        lbl_synths.setFont(lbl_synths.getFont().deriveFont(lbl_synths.getFont().getSize()-2f));
        org.openide.awt.Mnemonics.setLocalizedText(lbl_synths, org.openide.util.NbBundle.getMessage(OutputSynthToolbarPanel.class, "OutputSynthToolbarPanel.lbl_synths.text")); // NOI18N
        lbl_synths.setToolTipText(org.openide.util.NbBundle.getMessage(OutputSynthToolbarPanel.class, "OutputSynthToolbarPanel.lbl_synths.toolTipText")); // NOI18N
        pnl_labels.add(lbl_synths);

        add(pnl_labels);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jjazz.ui.flatcomponents.FlatButton fbtn_editOutputSynth;
    private org.jjazz.ui.flatcomponents.FlatButton fbtn_playbackTransposition;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel lbl_stdBanks;
    private javax.swing.JLabel lbl_synths;
    private javax.swing.JPanel pnl_labels;
    // End of variables declaration//GEN-END:variables

}
