/*
 *  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 * 
 *  Copyright @2019 Jerome Lelasseux. All rights reserved.
 *
 *  This file is part of the JJazzLabX software.
 *   
 *  JJazzLabX is free software: you can redistribute it and/or modify
 *  it under the terms of the Lesser GNU General Public License (LGPLv3) 
 *  as published by the Free Software Foundation, either version 3 of the License, 
 *  or (at your option) any later version.
 *
 *  JJazzLabX is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 * 
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with JJazzLabX.  If not, see <https://www.gnu.org/licenses/>
 * 
 *  Contributor(s): 
 */
package org.jjazz.notesviewer.guitar;

import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.JLabel;
import org.jjazz.leadsheet.chordleadsheet.api.item.CLI_ChordSymbol;
import org.jjazz.notesviewer.spi.NotesViewer;
import org.jjazz.ui.guitardiagramcomponent.api.GuitarDiagramComponent;
import org.jjazz.ui.guitardiagramcomponent.api.TGChord;
import org.jjazz.ui.guitardiagramcomponent.api.TGChordCreatorUtil;

public class GuitarNotesViewerComponent extends javax.swing.JPanel
{

    private GuitarNotesViewer notesViewer;
    private static final Logger LOGGER = Logger.getLogger(GuitarNotesViewerComponent.class.getSimpleName());

    /**
     * Creates new form PianoViewerComponent
     */
    public GuitarNotesViewerComponent(GuitarNotesViewer viewer)
    {
        notesViewer = viewer;

        initComponents();
    }

    public void clear()
    {
        pnl_instrument.removeAll();
        revalidate();
        repaint();
    }

    public void setMode(NotesViewer.Mode mode)
    {
        switch (mode)
        {
            case ShowBackingTrack:
                pnl_instrument.removeAll();
                pnl_instrument.add(new JLabel("Not supported"));
                break;
            case ShowSelection:
                clear();
                break;
            default:
                throw new AssertionError(mode.name());

        }
    }

    public void showDiagrams(CLI_ChordSymbol cliCs)
    {
        pnl_instrument.removeAll();
        List<TGChord> tgChords = new TGChordCreatorUtil().getChords(cliCs.getData());
        tgChords.stream().limit(30).forEach(tgChord ->
        {     
            GuitarDiagramComponent diagram = new GuitarDiagramComponent(tgChord);
            pnl_instrument.add(diagram);
        }
        );

        revalidate();
        repaint();
    }

    @Override
    public void setEnabled(boolean b
    )
    {
        super.setEnabled(b);
        for (GuitarDiagramComponent diagram : getDiagrams())
        {
            diagram.setEnabled(false);
        }
    }
    // ===============================================================================
    // Private methods
    // ===============================================================================

    private List<GuitarDiagramComponent> getDiagrams()
    {
        var res = new ArrayList<GuitarDiagramComponent>();
        for (Component c : pnl_instrument.getComponents())
        {
            if (c instanceof GuitarDiagramComponent)
            {
                res.add((GuitarDiagramComponent) c);
            }
        }
        return res;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
     * this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnl_instrument = new javax.swing.JPanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jScrollPane1.setViewportView(pnl_instrument);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnl_instrument;
    // End of variables declaration//GEN-END:variables
}
